spring.application.name=api-gateway
server.port=8082


spring.cloud.gateway.routes[0].id=quiz-service
spring.cloud.gateway.routes[0].uri=http://127.0.0.1:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz/**

spring.cloud.gateway.routes[1].id=attempt-service
spring.cloud.gateway.routes[1].uri=http://127.0.0.1:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/attempt/**